name: Publish website
on:
  push:
    tags:
      - 'v**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: yarn
      - name: Build
        run: cd apps/website && yarn build
      - name: Export
        run: cd apps/website && yarn export
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./apps/website/out