name: extension - zip
on:
  push:
    branches:
      - main
    tags:
      - 'v**\+ext'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: |-
          cd apps/extension
          yarn --ignore-engines
      - name: Run build
        run: |-
          cd apps/extension
          yarn build
      - uses: papeloto/action-zip@v1
        with:
          files: apps/extension/dist/chrome
          dest: chrome.zip
      - uses: papeloto/action-zip@v1
        with:
          files: apps/extension/dist/firefox/
          dest: firefox.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          files: |
            chrome.zip
            firefox.zip
