name: extension - zip
on:
  push:
    branches:
      - main
    tags:
      - 'v**\+ext'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: |-
          cd apps/extension
          yarn --ignore-engines
      - name: Run build
        run: |-
          cd apps/extension
          yarn build
      - name: Get version without prefix
        id: tmp
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: Remove version cmd suffix
        id: vars
        run: echo ::set-output name=tag::${TAG%+ext}
        env:
          TAG: ${{steps.tmp.outputs.tag}}
      - uses: actions/upload-artifact@v3
        with:
          name: chrome-${{ steps.vars.outputs.tag }}
          path: apps/extension/dist/chrome
      - uses: actions/upload-artifact@v3
        with:
          name: firefox-${{ steps.vars.outputs.tag }}
          path: apps/extension/dist/firefox/*