name: extension - test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/extension/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/extension/**'
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: |-
          cd apps/extension
          yarn --ignore-engines
      - name: Run build
        run: |-
          cd apps/extension
          yarn build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |-
          cd apps/extension
          yarn test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
