name: website - publish
on:
  push:
    tags:
      - 'v**\+web'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Install dependencies
        run: |-
          cd apps/website
          yarn
      - name: Run build
        run: |-
          cd apps/website
          yarn build
      - name: Run export
        run: |-
          cd apps/website
          yarn export
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./apps/website/out